Añadido servicio con sus métodos para cada endpoint
FundacioEsplaiJava2024/ToDoApi-grupo-1 pull request #5
Opened 2024-07-12 07:43 UTC by rvst312

Usamos: 
````
 @Autowired
    private TodoRepository todoRepository;
````
para no tener que declarar el constructor y que ya se inyecte automáticamente.
Y declaramos la lógica de cada endpoint en algunos casos usamos métodos propios de spring como por ejemplo:
````
public void addTask(ToDo todo) {
        this.todoRepository.save(todo);
    }

    public List<ToDo> getAllTask() {
        return this.todoRepository.findAll();
    }
````
y declaramos métodos "editTask", "closeTask" y "reOpenTask" que están por implementar.

2024-07-12 07:49 UTC, AngelCorral0 approved these changes
perfect

2024-07-12 07:52 UTC, Daniela-RL approved these changes

2024-07-12 09:28 UTC, SaraVictorFernandez commented
Tiene buena pinta. Cómo habéis comprobado que funciona correctamente?

2024-07-12 10:39 UTC, Davidvamosfull approved these changes

2024-07-12 10:42 UTC, AngelCorral0 approved these changes
me parece correcto

2024-07-12 10:43 UTC, Daniela-RL approved these changes

2024-07-12 10:56 UTC, rvst312 commented
@SaraVictorFernandez  He añadido los controles en esta versión. Ya se puede testear la API para comprobar que funciona correctamente. Faltaría por añadir los métodos en el servicio con la lógica para editar, cerrar task y abrir task. Se puede usar create task, get tasks y delete task por que están implementados con los propios de spring

2024-07-15 08:51 UTC, SaraVictorFernandez reviewed
Se os han duplicado las clases (con lo del case sensitive)

2024-07-15 08:51 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/model/TodoModel.java
Y esta clase vacía? Además, no coincide con el nombre del fichero que la contiene

2024-07-15 08:51 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/controller/TodoController.java
> +    public ResponseEntity<ToDo> todo(@RequestBody ToDo todo){
Aquí tenéis diferentes problemas

Aceptáis que no se mande ningún objeto
El usuario puede elegir el id de la tarea, puede repetir ids de tareas existentes
No sigue los estandars de api rest

2024-07-15 08:51 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/controller/TodoController.java
> +        todoService.deleteTask(toDoid);
Si la task no existe, me devuelve un ok. Está hecho expresamente?

2024-07-15 08:51 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/controller/todoController.java
Hay dos controllers????

2024-07-22 09:04 UTC, SaraVictorFernandez requested changes

2024-07-22 09:04 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/model/todoModel.java
> -public class ToDoModel {
The class name doesn't match the file name

2024-07-24 11:09 UTC, AngelCorral0 commented on todo-api/src/main/java/com/example/todo_api/model/TodoModel.java
En principio ya debería estar arreglado

2024-07-26 08:09 UTC, SaraVictorFernandez approved these changes
looks good

2024-07-26 10:41 UTC, merged