Connection ddbb
FundacioEsplaiJava2024/ToDoApi-grupo-1 pull request #8
Opened 2024-07-24 09:15 UTC by Daniela-RL

Establecer conexión con base de datos.
Se han añadido configuraciones en el fichero properties indicando el nombre de la base de datos, el puerto y url que utilizaremos para poder establecer la conexión.

2024-07-24 09:28 UTC, SaraVictorFernandez requested changes
Borra las clases que ya no tienen que estar :)

2024-07-24 09:28 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/controller/todoController.java
Esta clase se tiene que borrar

2024-07-24 09:28 UTC, SaraVictorFernandez commented on todo-api/src/main/java/com/example/todo_api/entity/toDo.java
Borra las clases que ya no tienen que estar

2024-07-26 08:59 UTC, closed without merging

2024-07-26 08:59 UTC, AngelCorral0 commented
se cierra debido a problemas con archivos y otras ramas